-- MySQL Script generated by MySQL Workbench
-- Wed Jul 25 10:52:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `challenge` DEFAULT CHARACTER SET utf8 ;
USE `challenge` ;

-- -----------------------------------------------------
-- Table `mydb`.`challenge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `challenge`.`challenge` ;

CREATE TABLE IF NOT EXISTS `challenge`.`challenge` (
  `seq` INT NOT NULL AUTO_INCREMENT,
  `yn` ENUM('y', 'n') NULL,
  `age` TINYINT(2) NULL,
  `birthday` VARCHAR(11) NULL,
  `bool` ENUM('true', 'false') NULL,
  `city` VARCHAR(45) NULL,
  `ccnumber` BIGINT(18) NULL,
  `date` VARCHAR(11) NULL,
  `digit` BIGINT(30) NULL,
  `dollar` VARCHAR(20) NULL,
  `first` VARCHAR(20) NULL,
  `chifre` BIGINT(12) NULL,
  `name` VARCHAR(60) NULL,
  `last` VARCHAR(45) NULL,
  `paragraph` LONGTEXT NULL,
  `sentence`LONGTEXT NULL,
  PRIMARY KEY (`seq`),
  UNIQUE INDEX `seq_UNIQUE` (`seq` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
