-- MySQL Script generated by MySQL Workbench
-- Wed Jul 25 10:52:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`challenge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`challenge` ;

CREATE TABLE IF NOT EXISTS `mydb`.`challenge` (
  `seq` INT NOT NULL AUTO_INCREMENT,
  `yn` VARCHAR(1) NULL,
  `age` TINYINT(2) NULL,
  `birthday` DATE NULL,
  `bool` TINYINT NULL,
  `city` VARCHAR(45) NULL,
  `ccnumber` BIGINT(18) NULL,
  `date` DATE NULL,
  `digit` BIGINT(10) NULL,
  `dollar` DECIMAL NULL,
  `first` VARCHAR(20) NULL,
  `chifre` BIGINT(12) NULL,
  `name` VARCHAR(60) NULL,
  `last` VARCHAR(45) NULL,
  `paragraph` LONGTEXT NULL,
  `sentence` MEDIUMTEXT NULL,
  PRIMARY KEY (`seq`),
  UNIQUE INDEX `seq_UNIQUE` (`seq` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
